[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.curl", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -d upload_max_filesize=10M -d post_max_size=10M -d memory_limit=128M -S 0.0.0.0:$PORT -t public"
